// <auto-generated />
using System;
using HandsOnMVCUsingEFCodeFirst_Demo2.Entties;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HandsOnMVCUsingEFCodeFirst_Demo2.Migrations
{
    [DbContext(typeof(MVCDB1128Context))]
    [Migration("20221208051009_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HandsOnMVCUsingEFCodeFirst_Demo2.Entties.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ProjectCode");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("HandsOnMVCUsingEFCodeFirst_Demo2.Entties.Project", b =>
                {
                    b.Property<string>("ProjectCode")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("ProjectCode");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("HandsOnMVCUsingEFCodeFirst_Demo2.Entties.Employee", b =>
                {
                    b.HasOne("HandsOnMVCUsingEFCodeFirst_Demo2.Entties.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectCode");

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
